name: Bug report
description: Report a reproducible problem in FinSight AI
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps
      placeholder: |
        1. Go to ...
        2. Upload ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Browser / OS / deployment target
